"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useMemo, useState } from "react";
import { ChevronRight, Menu, Minus, Plus, Search, ShoppingBag, Sparkles, Truck, X } from "lucide-react";

type View = "home" | "category" | "products" | "about" | "contact";
type Product = { name: string; category: string; price: number; color: string; texture: string; badge?: string };
const products: Product[] = [
  { name: "Aso-Oke Heritage Stripe", category: "Aso-Oke", price: 18500, color: "#183b8f", texture: "woven", badge: "Bestseller" },
  { name: "Saffron Royal Velvet", category: "Velvet", price: 14800, color: "#d69a20", texture: "velvet", badge: "New" },
  { name: "Ivory Cloud Linen", category: "Linen", price: 9200, color: "#e8ddc7", texture: "linen" },
  { name: "Adire Indigo Current", category: "Adire", price: 12750, color: "#163868", texture: "adire", badge: "Hand-dyed" },
  { name: "Coral Duchess Satin", category: "Satin", price: 10800, color: "#d96d55", texture: "satin" },
  { name: "Emerald Ankara Mosaic", category: "Ankara", price: 7900, color: "#0f6c50", texture: "ankara" },
  { name: "Midnight Italian Crepe", category: "Crepe", price: 11600, color: "#1b1d2a", texture: "crepe" },
  { name: "Champagne Bridal Lace", category: "Lace", price: 24500, color: "#c9a96e", texture: "lace", badge: "Limited" },
];
const categories = [
  { name: "Aso-Oke", note: "Ceremonial weaves" }, { name: "Lace", note: "Detailed & occasion-ready" },
  { name: "Ankara", note: "Bold everyday prints" }, { name: "Velvet", note: "Soft, rich drape" },
];
const storyCategories = [
  { name: "Seven Star", note: "Distinguished suiting" },
  { name: "German Wool", note: "Refined weight & finish" },
  { name: "Ceckers", note: "Classic checked designs" },
  { name: "Cashmere", note: "Exceptionally soft handle" },
  { name: "Irish", note: "Crisp premium tradition" },
  { name: "Stripes", note: "Sharp directional style" },
  { name: "Scabal", note: "Luxury tailoring cloth" },
  { name: "Plain & Pattern", note: "Versatile coordinated looks" },
];
const money = (amount: number) => `₦${amount.toLocaleString("en-NG")}`;

function Brand() { return <Link href="/" className="brand" aria-label="HSG Texture home"><span className="brand-mark">H</span><span><b>HSG</b><small>TEXTURE</small></span></Link>; }
function Header({ cart, openCart }: { cart: number; openCart: () => void }) {
  const [menu, setMenu] = useState(false); const [search, setSearch] = useState(false);
  const pathname = usePathname();
  const links = [{href:"/category",label:"Shop fabrics"},{href:"/products",label:"New arrivals"},{href:"/about",label:"Our story"},{href:"/contact",label:"Contact"}];
  return <><div className="announcement"><Sparkles size={14}/> New season edit: complimentary Lagos delivery over ₦75,000</div><header className="header"><Brand/><nav className={menu ? "nav open" : "nav"} aria-label="Main navigation">{links.map(link=>{const active=pathname===link.href||pathname.startsWith(`${link.href}/`);return <Link key={link.href} href={link.href} className={active?"active":""} aria-current={active?"page":undefined} onClick={()=>setMenu(false)}>{link.label}</Link>})}</nav><div className="header-actions"><button aria-label="Search" onClick={() => setSearch(v=>!v)}><Search size={20}/></button><button aria-label="Open shopping bag" onClick={openCart}><ShoppingBag size={20}/>{cart>0&&<span className="cart-count">{cart}</span>}</button><button className="menu-button" aria-label="Toggle menu" onClick={()=>setMenu(v=>!v)}>{menu?<X/>:<Menu/>}</button></div>{search&&<form className="search-panel" action="/products"><Search size={19}/><input name="q" autoFocus placeholder="Search linen, lace, velvet…"/><button>Search</button></form>}</header></>;
}
function Footer() { return <footer><div className="footer-main"><div><Brand/><p>Remarkable fabric, thoughtfully sourced for the clothes and spaces that mean the most.</p></div><div><b>Shop</b><Link href="/products">All fabrics</Link><Link href="/category">Collections</Link><Link href="/products">New arrivals</Link></div><div><b>Help</b><Link href="/contact">Contact us</Link><a href="#">Delivery</a><a href="#">Fabric care</a></div><div><b>Stay in the weave</b><p>New drops, fabric notes and studio stories.</p><form className="newsletter"><input type="email" aria-label="Email address" placeholder="Email address"/><button>Join</button></form></div></div><div className="footer-bottom"><span>© 2026 HSG Texture</span><span>Designed for makers everywhere.</span></div></footer>; }
function ProductCard({ product, add }: { product: Product; add: () => void }) { return <article className="product-card"><Link href={`/products?item=${encodeURIComponent(product.name)}`} className={`product-art ${product.texture}`} style={{"--swatch":product.color} as React.CSSProperties}>{product.badge&&<span className="badge">{product.badge}</span>}<span className="fabric-roll one"/><span className="fabric-roll two"/><span className="fabric-fold"/></Link><div className="product-info"><div><p>{product.category}</p><h3>{product.name}</h3><strong>{money(product.price)} <small>/ yard</small></strong></div><button aria-label={`Add ${product.name} to bag`} onClick={add}><ShoppingBag size={18}/></button></div></article>; }
function CartDrawer({ open, close, count }: {open:boolean;close:()=>void;count:number}) { return <div className={open?"cart-overlay show":"cart-overlay"} onClick={close}><aside onClick={e=>e.stopPropagation()}><div className="cart-title"><h2>Your bag</h2><button onClick={close} aria-label="Close bag"><X/></button></div>{count?<><div className="cart-item"><span className="mini-swatch"/><div><b>Curated fabric selection</b><p>{count} {count===1?"item":"items"} reserved</p><div className="qty"><button><Minus size={14}/></button><span>{count}</span><button><Plus size={14}/></button></div></div></div><div className="cart-total"><span>Estimated total</span><b>{money(count*14800)}</b></div><button className="primary full">Continue to checkout</button></>:<div className="empty-cart"><ShoppingBag size={36}/><h3>Your bag is empty</h3><p>Start with a texture that speaks to you.</p><Link href="/products" className="primary" onClick={close}>Browse fabrics</Link></div>}</aside></div>; }

function HomeView({add}:{add:()=>void}) { return <main><section className="hero"><div className="hero-copy"><p className="eyebrow">The new textile edit</p><h1>Find the fabric.<br/><em>Make it yours.</em></h1><p>Exceptional textures for defining moments—from everyday silhouettes to once-in-a-lifetime celebrations.</p><div className="hero-buttons"><Link href="/products" className="primary">Shop new arrivals</Link><Link href="/category" className="text-link">Explore collections <ChevronRight size={16}/></Link></div><div className="hero-trust"><span><Truck size={17}/> Nationwide delivery</span><span><Sparkles size={17}/> Curated quality</span></div></div><div className="hero-image" role="img" aria-label="Blue, gold, ivory and patterned fabrics"><span className="image-note"><i/> Texture you can almost feel</span></div></section><section className="category-section"><SectionTitle eyebrow="Shop by mood" title="A texture for every story" href="/category" link="View every collection"/><div className="category-grid">{storyCategories.map((c,i)=><Link href={`/products?category=${encodeURIComponent(c.name)}`} key={c.name} className={`category-card c${i%4}`}><span className="category-text"><small>{String(i+1).padStart(2,"0")}</small><b>{c.name}</b><p>{c.note}</p></span></Link>)}</div></section><section className="products-section"><SectionTitle eyebrow="Just in" title="Fresh from the cutting table" href="/products" link="Shop all fabrics"/><div className="product-grid">{products.slice(0,4).map(p=><ProductCard key={p.name} product={p} add={add}/>)}</div></section><section className="studio-story"><div><p className="eyebrow">The HSG standard</p><h2>Chosen by hand.<br/>Made to be remembered.</h2></div><div><p>We look beyond colour. Every fabric in our edit is selected for its handle, fall, finish and the way it transforms in the hands of a maker.</p><Link href="/about" className="text-link light">Meet HSG Texture <ChevronRight size={16}/></Link></div></section><section className="service-grid">{[["01","Swatch-ready","See and feel a fabric before committing to yardage."],["02","Measured with care","Every cut is checked twice and packed with intention."],["03","Human guidance","Tell us what you’re making; we’ll help you choose well."]].map(x=><div key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</section></main>; }
function SectionTitle({eyebrow,title,href,link}:{eyebrow:string;title:string;href:string;link:string}) { return <div className="section-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div><Link href={href}>{link} <ChevronRight size={16}/></Link></div>; }
function Listing({category=false,add}:{category?:boolean;add:()=>void}) { const [filter,setFilter]=useState("All"); const shown=useMemo(()=>filter==="All"?products:products.filter(p=>p.category===filter),[filter]); return <main><section className="listing-hero"><p className="eyebrow">{category?"The fabric library":"Shop the edit"}</p><h1>{category?"Collections with character":"Fabrics worth making with"}</h1><p>{category?"Explore our materials by tradition, finish and feel.":"Curated textiles, sold by the yard and ready for your next idea."}</p></section>{category&&<div className="category-banner-grid">{categories.map((c,i)=><button key={c.name} onClick={()=>setFilter(c.name)} className={`category-banner c${i}`}><span>{c.name}</span><small>{c.note}</small></button>)}</div>}<section className="catalog"><div className="catalog-tools"><p><b>{shown.length}</b> fabrics</p><div className="filters">{["All","Aso-Oke","Lace","Ankara","Velvet"].map(x=><button className={filter===x?"active":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div></div><div className="product-grid">{shown.map(p=><ProductCard key={p.name} product={p} add={add}/>)}</div></section></main>; }
function About() { return <main><section className="about-hero"><div><p className="eyebrow">Our story</p><h1>Fabric is where every great idea begins.</h1></div><div className="about-collage"><span/><span/><span/></div></section><section className="about-copy"><p className="big-copy">HSG Texture brings the discovery and delight of a great fabric market into a calm, considered shopping experience.</p><div><p>We started with a simple belief: choosing fabric should feel as inspiring as wearing the finished piece. So we source in small, intentional edits—prioritising beautiful hand-feel, dependable quality and colours that come alive in natural light.</p><p>From heritage occasion cloth to easy linens and statement prints, our collection is made for designers, tailors, stylists and curious first-time makers.</p></div></section><section className="values"><p className="eyebrow">What guides us</p><div>{[["01","Quality in the hand","We choose fabrics by touch, drape and durability—not just appearance."],["02","Heritage, kept alive","We champion textiles and techniques with stories worth carrying forward."],["03","Service, person to person","Thoughtful help from people who know fabric and respect your vision."]].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section></main>; }
function Contact() { return <main className="contact-page"><section><p className="eyebrow">Visit or write</p><h1>Let’s find your fabric.</h1><p>Share the idea, colour or occasion you have in mind. Our fabric team will guide you from there.</p><div className="contact-details"><div><small>Studio</small><b>12 Admiralty Way, Lekki<br/>Lagos, Nigeria</b></div><div><small>Call / WhatsApp</small><b>+234 810 705 0824</b></div><div><small>Hours</small><b>Mon–Sat, 9am–6pm</b></div></div></section><form className="contact-form" onSubmit={e=>{e.preventDefault();alert("Thank you — the HSG Texture team will be in touch.")}}><label>Name<input required placeholder="Your name"/></label><label>Email<input required type="email" placeholder="you@example.com"/></label><label>What are you making?<select><option>Everyday wear</option><option>Wedding or occasion</option><option>Interior project</option><option>Something else</option></select></label><label>Tell us more<textarea rows={5} placeholder="Colours, quantity, date, inspiration…"/></label><button className="primary">Send enquiry</button></form></main>; }
function WhatsAppButton() { return <a className="whatsapp-button" href="https://wa.me/2348107050824?text=Hello%20HSG%20Texture%2C%20I%27d%20like%20help%20choosing%20a%20fabric." target="_blank" rel="noopener noreferrer" aria-label="Chat with HSG Texture on WhatsApp"><svg viewBox="0 0 32 32" aria-hidden="true"><path fill="currentColor" d="M16.04 3A12.9 12.9 0 0 0 5.03 22.62L3.2 29l6.53-1.71A12.97 12.97 0 1 0 16.04 3Zm0 23.77c-1.9 0-3.76-.5-5.38-1.44l-.39-.23-3.87 1.02 1.03-3.77-.25-.4a10.72 10.72 0 1 1 8.86 4.82Zm5.88-8.04c-.32-.16-1.9-.94-2.2-1.05-.29-.11-.5-.16-.72.16-.21.33-.82 1.05-1 1.27-.19.21-.38.24-.7.08-.32-.16-1.36-.5-2.59-1.6a9.68 9.68 0 0 1-1.79-2.23c-.19-.32-.02-.5.14-.66.15-.14.33-.37.49-.56.16-.19.21-.32.32-.54.11-.21.05-.4-.03-.56-.08-.16-.72-1.73-.98-2.37-.26-.62-.52-.54-.72-.55h-.61c-.22 0-.57.08-.86.4-.3.33-1.13 1.11-1.13 2.7s1.16 3.13 1.32 3.35c.16.21 2.28 3.48 5.52 4.88.77.33 1.37.53 1.84.68.77.24 1.47.21 2.03.13.62-.09 1.9-.78 2.17-1.53.27-.76.27-1.41.19-1.54-.08-.14-.3-.22-.62-.38Z"/></svg><span>Chat with us</span></a>; }
export function Storefront({view}:{view:View}) { const [cart,setCart]=useState(0);const [drawer,setDrawer]=useState(false);const add=()=>{setCart(c=>c+1);setDrawer(true)};return <div><Header cart={cart} openCart={()=>setDrawer(true)}/>{view==="home"&&<HomeView add={add}/>} {view==="category"&&<Listing category add={add}/>} {view==="products"&&<Listing add={add}/>} {view==="about"&&<About/>} {view==="contact"&&<Contact/>}<Footer/><WhatsAppButton/><CartDrawer open={drawer} close={()=>setDrawer(false)} count={cart}/></div>; }
